### ISSUE TITLE
error with modeler 3.4.1

### ISSUE THREAD

**Issue by ofthewood** [camunda/camunda-modeler-custom-linter-rules-plugin#1]
hello, 

I can't rebuild this plugin and use it with modeler 3.4.1
Is there a workaround ? 

> Failed to instantiate component     Diagram.js:56

> Error: No provider for "linting"! (Resolving: alignToOrigin -> linting)  Diagram.js:57

**Comment by ofthewood** [comment]
bpmn linter was not installed

**Comment by barmac** [comment]
Opened accidentally.
