### ISSUE TITLE
Extend the README.MD to specify how namespaces are defined

### ISSUE THREAD

**Issue by Zyboarg** [camunda/camunda-modeler-custom-linter-rules-plugin#2]
After trying to write my own rules for your bpmnlint plugin I was slightly confused as to how the namespace `custom` was resolved. 
After some fiddling around I noticed that you guys actually scan the dependency names for strings that start with bpmnlint-plugin-.*

```
Error: Cannot resolve config <recommended> from <bpmnlint-plugin-cusdtom>
    at NodeResolver.resolveConfig (C:\Users\[userpath]\node_modules\bpmnlint\lib\resolver\n
ode-resolver.js:54:9)
    at Linter.resolveConfig (C:\Users\[userpath]\node_modules\bpmnlint\lib\linter.js:122:40
)
```

To avoid confusion with other devs coming to this project and wondering how they could define their custom namespace I'd like to recommend to add some more details in the README.MD. If you'd like I could extend the readme in a merge request for you. @nikku 

Niklas

**Comment by nikku** [comment]
Thanks for sharing your feedback. This is definitly a stumbling block we should avoid.

I'd love to take your contribution. Please propose an improvement as a PR.

**Comment by Zyboarg** [comment]
Alright cool. I'll write something up when I have time this week.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin/pull/3.
