### ISSUE TITLE
cant get it running in modeler

### ISSUE THREAD

**Issue by FO-e-X** [camunda/camunda-modeler-custom-linter-rules-plugin#4]
Hi,

I cant get the custom-linter-rules-plugin running in my modeler. How or where I have to put it to get it running in Modeler v3.5.0 with camunda-modeler-linter-plugin? 

If I install it as a standalone plugin the Modeler says "Linter- Custom Rules <error>". When I try to modify the camunda-modeler-linter-plugin .bpmnlintrc to get some errors shown as warning, the linter-plugin ignores it. After putting the custom-linter-rules-plugin as subdirectory of the camunda-modeler-linter-plugin the own .bpmnlintrc is still ignored... Putting the bpmnlint-plugin-custom directory directly into the camunda-modeler-linter-plugin directory also will not work.

The Modeler-Log do not show any error. It looks like the custom rules and the modification of .bpmnlintrc "rules" will be ignored in all ways I tried.

So, how the custom rules can be used? The description isn't clear enough (to me) to know where to place it.

Regards
Frank

**Comment by nikku** [comment]
Hello @FO-e-X!

Did you bundle the plug-in after you made changes to the `.bpmnlintrc` file?

This is documented [here](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin#bundling).

We are open to feedback how we can improve the existing documentation.

**Comment by FO-e-X** [comment]
Hi @nikku ,

thanks for your hint. I missed this step...  👍 

I did not realized, that a rebuild is required, I thought this config-file is parsed at start of the Camunda Modeler during initializing all plugins. BTW, this would be fantastic and a bit easier to understand for none-NodeJS-guys :) For you as NodeJS specialist its very easy, I think. 👍 

Now I have to search for a solution to get NodeJS running here in this enterprise environment, downloading is restricted for most cases. I.e I cant download the Modeler, this must be provided from other guys here. But I can download ZIPs from GitHub... So it would be really great to configure and use the plugins without using other tools like Node Package Manager to bundle the new config.

Regards
Frank
