### ISSUE TITLE
Instructions on how to install it not clearly defined 

### ISSUE THREAD

**Issue by bassgelo** [camunda/camunda-modeler-custom-linter-rules-plugin#42]
Hi guys,

I am struggling to install the plugin.  I cannot get it to run.

Apparently the steps you need are either not documented or there is subtle flow that is not explicit.

My struggles:

-Documentation does not mention if the whole folder has to be added to /resources/plugins of the Camunda Modeler installation or just parts, so missing some explanation of the structure.
-Documentation contains a section Bundling but there is no context when to do this, or why, so this very step assumes too much, a non technical user (no NodeJS user) cannot completely get it.
-An example on how to do it or a describing the installation in a list would be fantastic.

Regards

**Comment by nikku** [comment]
From what I understood you are struggling to get the plug-in integrated into the Desktop Modeler. Please checkout the [general plug-ins documentation](https://docs.camunda.io/docs/components/modeler/desktop-modeler/plugins/#plugging-into-camunda-modeler) that contains important information about how to work with Desktop Modeler plug-ins.

I also [updated the README](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin/blob/master/README.md#development) to better reflect integrating the plug-in into the modeler.
