### ISSUE TITLE
Check in the bundled plugin in the repo

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler-custom-linter-rules-plugin#44]
Right now, you cannot just `git clone` the plugin and run it. This leads to an error, and a user has to `npm install && npm run all` before usage. This should not be required.

**Comment by nikku** [comment]
To be verified: Does this [follow the standard structure of plug-ins](https://github.com/camunda/camunda-modeler-plugins)? Let's ensure users can get and install this plug-in as they can install others.

**Comment by barmac** [comment]
In the plugins repo, the bundle is placed in `client/client.bundle.js` (e.g. https://github.com/camunda/camunda-modeler-plugins/blob/main/bpmn-js-plugin-example/client/client.bundle.js). In this plugin, we use `dist` directory. We could adjust it when fixing this issue.
