### ISSUE TITLE
multiple rule-sets as own modeler-custom-linter-rules-plugins do not work together

### ISSUE THREAD

**Issue by FO-e-X** [camunda/camunda-modeler-custom-linter-rules-plugin#5]
Hello,

after passing some experiments with new rules I decided to build different rule-sets, depending on the duty of the user. Lets assume we have some special rules for business analysts. And lets assume too, that a developer should use the same rules and some other rules on top. So the plan is, build a custom-rules-plugin for BAs and another one for DEVs. To prevent from useless code the DEV should be able to use rules from BA-rule-set and other rules from DEV-rule-set.

Now I builded 2 different plugins without copying any rule. In Modeler both plugins are shown and the expectation is, rules of both rule-sets are used. But this is not happening. I only get results from DEV-rules, BA-rules are ignored (bpmn is designed to hit rules of both). Mabye it depends on the alphabetical order, wich rule-set is used.

I took a deeper look at the plugin configuration and changed the namespaces and rule-directories properly (clean npm install and run all without errors or wrong generated packages). So I have 2 completly seperated custom-rule-plugins, designed to work together as rule-modules. But still only 1 rule-set is used.

I'm sorry... I didn't put any screenshots or code in here, because both different plugins work seperatly and also all rules are working combined in one plugin. So I think there is no mistake in the rule configuration. And because of different namespaces in both plugin there should be no error at this place. The question is simply: Why 2 custom-linter-rules-plugins do not work together?

Do you have any idea?

Yes, I know... I can put all required rules into 1 set and rebundle it depending for the required duty. This way works but has some more efforts when changing a rule in a basic rule-set like BA-rules. So I have to rebundle multiple plugins instead of rebundling only one rule-module with changes.

Regards
Frank

**Comment by nikku** [comment]
Please provide us a setup that allows us to reproduce your issue. 

As an example, you could share your modeler-custom-linter-rules project.

**Comment by FO-e-X** [comment]
Hi Nikku,

as you recommended I uploaded both projects.

[camunda-modeler-custom-linter-rules-plugin-nlb-ba.zip](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin/files/4225165/camunda-modeler-custom-linter-rules-plugin-nlb-ba.zip)
[camunda-modeler-custom-linter-rules-plugin-nlb-dev.zip](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin/files/4225166/camunda-modeler-custom-linter-rules-plugin-nlb-dev.zip)

I put both project into the Modeler plugin directory. The Modeler shows BPMN Linter in Black, BPMN-Linter BA Rules and BPMN-Linter Dev Rules in grey. BA Rules contains 2 rules, Dev Rules contains 1 other rule. All 3 rules in 1 plugin are working good. Splittet in 2 plugins only the 1 Dev Rules rule is working...

**Comment by FO-e-X** [comment]
I found a "," to much in the "index.js" of the rule plugin directory "bpmnlint-plugin-nlbba". But even after deleting the "," and rebundle the Modeler plugin, it will not work together with the oder Modeler plugin...

**Comment by FO-e-X** [comment]
Hi @nikku ,

could you have a look at the problem using my 2 custom-linter-rules-plugins?
As I mentioned, the misplaced comma didn't fix the problem for me.

Regards
Frank

**Comment by nikku** [comment]
I was finally able to wrap my head around this issue and the fixtures you provided.

To verify I understood your use case: You'd expect that injected rule sets are merged together. 

At the moment, the last loaded plug-in wins, so that is an enhancement. Right now [the API and documentation](https://github.com/camunda/camunda-modeler-linter-plugin#overriding-provided-rules) should also be quite clear about this behavior.

If we consider future versions of the library I could imagine a number of things:

* Multiple plug-ins are able to provide rules
* Per default, all rules are merged (with the default rules even?)
* The user is able to choose which rules to activate, i.e. via the existing UI

An example how user UI controls may look like is sketched below:

![image](https://user-images.githubusercontent.com/58601/75884127-92073180-5e24-11ea-866e-2a5b46204b81.png)

**Comment by nikku** [comment]
I've opened https://github.com/camunda/camunda-modeler-linter-plugin/issues/8. It should reflect your use case (and is in the right place as the capability is really missing in `camunda-modeler-linter-plugin`). 

Closing this issue in favor of https://github.com/camunda/camunda-modeler-linter-plugin/issues/8.
