### ISSUE TITLE
no-disconnected claims an event-based subprocess as error in camunda-modeler-linter-plugin

### ISSUE THREAD

**Issue by FO-e-X** [camunda/camunda-modeler-custom-linter-rules-plugin#6]
![rule_not-connected_error](https://user-images.githubusercontent.com/36297434/75439056-5fa79100-5959-11ea-9478-224c476d6c46.png)

I verified the rule-code by comparing 
https://github.com/bpmn-io/bpmnlint/blob/master/rules/no-disconnected.js
with the version downloaded with NPM...

The reason and solution is simple: 
- bpmnlint is in version 6.3.0 and contains the fix. https://github.com/bpmn-io/bpmnlint/blob/master/package.json
- camunda-modeler-linter-plugin refers to bpmnlint 6.2.0 https://github.com/camunda/camunda-modeler-linter-plugin/blob/master/package.json
- camunda-modeler-custom-linter-rules-plugin refers to bpmnlint 6.1.0 https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin/blob/master/package.json

Please update the modeler plugins. I did it at my machine and it works fine 👍 

Regards
Frank

**Comment by nikku** [comment]
Will do.

Thanks for reproducing this and tracking down the issue :+1:

**Comment by nikku** [comment]
Published a new version of the stock lint rules plug-in that fixes the issue. 

![image](https://user-images.githubusercontent.com/58601/75526353-ecae2100-5a11-11ea-8a80-7e5b25a50127.png)
