### ISSUE TITLE
Checking camunda ExtensionElements

### ISSUE THREAD

**Issue by silvanbrenner** [camunda/camunda-modeler-custom-linter-rules-plugin#8]
Hi camunda team

Is it's possible to check some specific extension elements?

`
      <bpmn:extensionElements>
        <camunda:properties>
          <camunda:property name="ToCheckA" />
          <camunda:property name="ToCheckB" />
        </camunda:properties>
      </bpmn:extensionElements>
`

I tried something like `node.extensionElements` to get all extension elements, but it's not working.

**Comment by philippfromme** [comment]
You should have access to the `extensionElements` property. Can you provide an example diagram that you want to lint?

**Comment by silvanbrenner** [comment]
Sorry my mistake :)

I found a solution:
```
      const extensionElements = node.extensionElements;
      if(extensionElements.values !== undefined) {
        const elements = node.extensionElements.values || [];
        elements.forEach((extElement) => {
          if(extElement.values.length >= 1) {
              extElement.values.forEach((property) => {
                if(property.name !== 'Comment') {
                  reporter.report(node.id,  'Wrong value!');
                }
            });
          }
        });
      }
```
